services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=dpg-cor15qi0si5c739a9ngg-a.frankfurt-postgres.render.com;Port=5432;Database=database_for_webapp;Username=myuser;Password=fcpaLJnEXjO4oX74VZRERb0gJkJgnuss;Pooling=true;
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys  
volumes:
  dataprotection_keys: